[package]
name = "sample-duck"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
eframe = "0.32.3"
egui = "0.32.3"
egui_extras = "0.32.3"
rusqlite = { version = "0.37", features = ["bundled"] }
symphonia = "0.5.4"
walkdir = "2.5.0"
